% ssdescription/hddvcm_ss.m
Sys_Pc_vcm_c1=ss(0);
for i=1:length(omega_vcm)
	Sys_Pc_vcm_c1=Sys_Pc_vcm_c1+Kp_vcm*ss(...
    [0 1; -omega_vcm(i)^2 -2*zeta_vcm(i)*omega_vcm(i)],...
    [0; kappa_vcm(i)],...
    [1 0],...
    0);
end
